### ISSUE TITLE
ERROR: manifest for itmicus/cmdbuild:app-3.2 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by KuangFJ** [itmicus/cmdbuild_docker#13]
Hi,
I tried to deploy cmdbuild 3.2 by docker-compose, but I got the error as below.
I saw there was a similar issue has been closed. Could you please help me resolve this as well?

> docker-compose up -d
> Creating network "32_default" with the default driver
> Creating volume "32_cmdbuild-db" with default driver
> Creating volume "32_cmdbuild-tomcat" with default driver
> Pulling cmdbuild_db (itmicus/cmdbuild:db-3.0)...
> db-3.0: Pulling from itmicus/cmdbuild
> ...
> Status: Downloaded newer image for itmicus/cmdbuild:db-3.0
> Pulling cmdbuild_app (itmicus/cmdbuild:app-3.2)...
> ERROR: manifest for itmicus/cmdbuild:app-3.2 not found: manifest unknown: manifest unknown

**Comment by jonlynch** [comment]
I don't think there is an app-3.2 tag in docker hub.

**Comment by KuangFJ** [comment]
You are right.
I could build app-3.2 image from the Dockerfile without problems. My issue's solved.
Thank you for the message.
