### ISSUE TITLE
CMDBuild 3.3 and OpenMaint 2.1

### ISSUE THREAD

**Issue by biker2000on** [itmicus/cmdbuild_docker#19]
Hi, 

The new versions of OpenMaint and Ready2Use were released yesterday. Can you please update these so we can build containers with the new versions?

Thanks,
Justin

**Comment by afcarvalho-dev** [comment]
I don't mind sharing a new deployable version if @itmicus allows me to

**Comment by afcarvalho1991** [comment]
(ongoing will make a pull request soon)

**Comment by afcarvalho1991** [comment]
When allowed to I will make a pull request @itmicus ! Otherwise I will create a fork :)

**Comment by afcarvalho1991** [comment]
@itmicus please invite this account @afcarvalho1991 instead of the afcarvalho-dev. 

I have everything ready 👍

**Comment by itmicus** [comment]
> @itmicus please invite this account @afcarvalho1991 instead of @afcarvalho-dev.
> 
> I have everything ready 👍

i did it ) welcome

**Comment by afcarvalho1991** [comment]
@biker2000on you can now use this branch and build the docker image (locally)

    git clone https://github.com/itmicus/cmdbuild_docker
    git checkout add-cmdbuild-3.3

To build the images use: 

    docker build -t itmicus/cmdbuild:db-3.0 3.0/postgres/. --label "version=1.0" --label "maintaner=Itmicus <order@itmicus.ru>"
    docker build -t itmicus/cmdbuild:om-2.0-3.3 openmaint-2.0-3.3/. --label "version=1.0" --label "maintaner=Itmicus <order@itmicus.ru>"

To deploy the database and openmaint:

    cd openmaint-2.0-3.3/
    docker-compose up
  
  Should now be up and running after a 1 minute or 2 minutes.
  http://localhost:8090/cmdbuild

If you have any questions just ask!

**Comment by biker2000on** [comment]
Perfect. Thank you.
