### ISSUE TITLE
ERROR: manifest for itmicus/cmdbuild:r2u-2.0-3.3 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by anirimot** [itmicus/cmdbuild_docker#21]
I have a ERROR.

docker-compose up -d
 ↓
Pulling cmdbuild_app (itmicus/cmdbuild:r2u-2.0-3.3)...
ERROR: manifest for itmicus/cmdbuild:r2u-2.0-3.3 not found: manifest unknown: manifest unknown

**Comment by afcarvalho1991** [comment]
Perhaps you need to build the image locally, I don't know if @itmicus sent the images to dockerhub.

Wait a few hours I will send you the command to compile it.

**Comment by anirimot** [comment]
> 
> 
> Perhaps you need to build the image locally, I don't know if @itmicus sent the images to dockerhub.
> 
> Wait a few hours I will send you the command to compile it.

Thank you for your response.I am waiting.

**Comment by afcarvalho1991** [comment]
You need to first generate the image (locally), the image `itmicus/cmdbuild:r2u-2.0-3.3` is not published at docker hub [see here](https://hub.docker.com/r/itmicus/cmdbuild). 
As a result, you need to compile the Dockerfile yourself (see image below), the commands `docker run` and `docker pull` won't work for you because the image `itmicus/cmdbuild:r2u-2.0-3.3` hasn't been published. 

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/4429239/96834492-0507fb80-143a-11eb-8e55-9de326858bf0.png">

Thus, the steps to follow are: 

    docker build -t itmicus/cmdbuild:r2u-2.0-3.3 ready2use-2.0-3.3/. --label "version=1.0" --label "maintaner=Itmicus <order@itmicus.ru>"
    cd ready2use-2.0-3.3
    docker-compose up
    
    #wait a few minutes until you see something like this on your terminal
    
    #cmdbuild_app  | 22-Oct-2020 06:47:26.231 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [86] ms
    #cmdbuild_app  | 22-Oct-2020 06:47:26.266 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
    #cmdbuild_app  | 22-Oct-2020 06:47:26.349 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [43,504] milliseconds

Then access the following URL to your CMDBUILD website:
 - http://localhost:8090/cmdbuild

That is it. 

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/4429239/96835649-c96e3100-143b-11eb-8426-3c205bd95050.png">

André Carvalho.

**Comment by mmmmarcel** [comment]
Hi I have the same issue:
root@*****:~/cmdbuild_docker/ready2use-2.0-3.3# docker-compose up -d
Pulling cmdbuild_app (itmicus/cmdbuild:r2u-2.0-3.3)...
ERROR: manifest for itmicus/cmdbuild:r2u-2.0-3.3 not found: manifest unknown: manifest unknown


# docker build -t itmicus/cmdbuild:r2u-2.0-3.3 ready2use-2.0-3.3/. --label "version=1.0" --label "maintaner=Itmicus <order@itmicus.ru>"

result:
 ---> Running in 6dc1dfc623df
+ groupadd tomcat
+ useradd -s /bin/false -g tomcat -d /usr/local/tomcat tomcat
+ cd /tmp
+ wget -O cmdbuild.war https://sourceforge.net/projects/cmdbuild/files/ready2use-2.0/Core%20updates/ready2use-2.0-3.3/ready2use-2.0-3.3.war/download
--2022-11-08 13:31:13--  https://sourceforge.net/projects/cmdbuild/files/ready2use-2.0/Core%20updates/ready2use-2.0-3.3/ready2use-2.0-3.3.war/download
Resolving sourceforge.net (sourceforge.net)... 104.18.10.128, 104.18.11.128, 2606:4700::6812:b80, ...
Connecting to sourceforge.net (sourceforge.net)|104.18.10.128|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.sourceforge.net/project/cmdbuild/ready2use-2.0/Core%20updates/ready2use-2.0-3.3/ready2use-2.0-3.3.war?ts=gAAAAABjalohGtdW3peW4IBn4XVjfr5XuQ8Diy9s4HGwhRHo_eOn2fmuDECcecx2o2qEsj3hFF6uC1SG3PZVSYG6bh2rWN04PQ%3D%3D&use_mirror=master&r= [following]
--2022-11-08 13:31:13--  https://downloads.sourceforge.net/project/cmdbuild/ready2use-2.0/Core%20updates/ready2use-2.0-3.3/ready2use-2.0-3.3.war?ts=gAAAAABjalohGtdW3peW4IBn4XVjfr5XuQ8Diy9s4HGwhRHo_eOn2fmuDECcecx2o2qEsj3hFF6uC1SG3PZVSYG6bh2rWN04PQ%3D%3D&use_mirror=master&r=
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:443... connected.
**ERROR: The certificate of ‘downloads.sourceforge.net’ is not trusted.
ERROR: The certificate of ‘downloads.sourceforge.net’ has expired.**
The command '/bin/sh -c set -x  && groupadd tomcat      && useradd -s /bin/false -g tomcat -d $CATALINA_HOME tomcat     && cd /tmp      && wget -O cmdbuild.war "$CMDBUILD_URL"         && chmod 777 cmdbuild.war     && chmod 777 /usr/local/bin/docker-entrypoint.sh        && unzip cmdbuild.war -d cmdbuild       && mv cmdbuild.war $CATALINA_HOME/webapps/cmdbuild.war  && mv cmdbuild/* $CATALINA_HOME/webapps/cmdbuild/     && chmod 777 $CATALINA_HOME/webapps/cmdbuild/cmdbuild.sh        && chown tomcat -R $CATALINA_HOME       && cd /tmp      && rm -rf *     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 5
root@mit-rje-ws-0012:~/cmdbuild_docker# cd ready2use-2.0
ready2use-2.0/
ready2use-2.0-3.1.1/
ready2use-2.0-3.2/
ready2use-2.0-3.2.1/
ready2use-2.0-3.3/
ready2use-2.0-3.3.war?ts=gAAAAABjalNtrPT5FNl_PN49eVrwRCw5HJtwr6MUghoRtNuyareJKw93oPNZS35mslQ28hiXlxWRF4dkICAC3Jnc8BPTVXE-Ww==
root@*****:~/cmdbuild_docker# 

Any idea?
