### ISSUE TITLE
Failed to executing the command 'docker-compose up -d' for the cmdbuild 3.3 release

### ISSUE THREAD

**Issue by Alba-404** [itmicus/cmdbuild_docker#24]
I've downloaded the docker-compose.yml file for the CMDbuild 3.3 release. Each time I try to run 'docker-compose up -d' command, the execution fails, retrieving the  following error: "ERROR: manifest for itmicus/cmdbuild:app-3.3 not found: manifest unknown: manifest unknown". Have you any ideas on how to fix it?

Thank you.

**Comment by afcarvalho1991** [comment]
please refer to: https://github.com/itmicus/cmdbuild_docker/issues/22

Also, note that you have to download the whole folder, not just the docker-compose.yml!
