### ISSUE TITLE
TODO: Update cmdbuild:db-3.0 from postgres:10.7 to postgres:10.23-bullseye

### ISSUE THREAD

**Issue by afcarvalho1991** [itmicus/cmdbuild_docker#37]
### Update cmdbuild:db-3.0 from postgres:10.7 to postgres:10.23-bullseye

- Could and should be updated to [10.23-bullseye](https://hub.docker.com/layers/library/postgres/10.23-bullseye/images/sha256-815cad300033950cbb302a1997cbe7769378e2760c08d48cfebb60c25e40b6ce?context=explore) 
- Target Dockerfile is [File](https://github.com/itmicus/cmdbuild_docker/blob/master/3.0/postgres/Dockerfile)

> When completed I can push the image to the dockerhub`afcarvalho1991/cmdbuild:db-3.0` and update all the docker-compose files that are currently using the image `itmicus/cmdbuild:db-3.0`

**Comment by itmicus** [comment]
#42 fixed
