### ISSUE TITLE
Incorrect usage of shorthand flag '-d' in the command "docker compose -d -f openmaint-2.3-3.4.1-d/docker-compose.yml up"

### ISSUE THREAD

**Issue by sandamn2036** [itmicus/cmdbuild_docker#39]
The README.md file and the Github page of the project suggest using the command "docker compose -d -f openmaint-2.3-3.4.1-d/docker-compose.yml up" to start the project. However, when running the command, the output shows an error message "unknown shorthand flag: 'd' in -d".

Expected behavior: The command should start the project without any errors.

Actual behavior: The command fails to start the project due to incorrect usage of the shorthand flag.

Steps to reproduce:

    Clone the repository from Github.
    Navigate to the project directory.
    Run the command "docker compose -d -f openmaint-2.3-3.4.1-d/docker-compose.yml up".
    The output shows an error message "unknown shorthand flag: 'd' in -d".

Proposed solution: The correct usage of the shorthand flag is "-d" instead of "-d". The correct command is "docker-compose -f openmaint-2.3-3.4.1-d/docker-compose.yml up -dl".

Impact: The incorrect usage of the shorthand flag in the command can cause confusion for new users trying to start the project. It can also lead to wasted time and effort trying to troubleshoot the issue.

Recommendation: Update the README.md file and the Github page of the project with the correct command to start the project.

**Comment by itmicus** [comment]
thank you, it is fixed https://github.com/itmicus/cmdbuild_docker/commit/a2ee960b522fce625418490e95cc0e761ab3b769
