### ISSUE TITLE
DataBase issue "Could not create any assest or building"

### ISSUE THREAD

**Issue by Abady-01** [itmicus/cmdbuild_docker#42]
Hi all i installed openmaint with last update version 2.3-3.4.1-d and deployed by docker compose but i cannot create or save anything this some of error:

2023-07-16 11:07:53.790 UTC [114] DETAIL:  Failing row contains (401639, "Building", 100, null, null, null, 2023-07-16 11:07:53.790409+00, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 100, null, null, null, null, null, null, null, null, null, null).
openmaint_db     | 2023-07-16 11:07:53.790 UTC [114] STATEMENT:  INSERT INTO "Building" ("Code", "Description", "Name", "MainUse", "State", "Complex", "Address", "ZIP", "City", "Coordinates", "Condition", "Criticality", "TotalFloors", "TotalUnits", "TotalRooms", "GlazedArea", "CleanableArea", "CoveredArea", "TotalNetArea", "TotalGrossArea", "TotalHeatedVolume", "TotalVolume", "ServiceStatus", "CalendarEntity", "IdTenant") VALUES ('100', NULL, '100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) RETURNING "Id"
openmaint_db     | 2023-07-16 11:10:38.745 UTC [112] ERROR:  null value in column "CurrentId" violates not-null constraint
openmaint_db     | 2023-07-16 11:10:38.745 UTC [112] DETAIL:  Failing row contains (401769, "Component", 10, null, null, null, 2023-07-16 11:10:38.745204+00, null, null, null, null, 379526, 280414, null, null, null, null, null, null, null, 382605, 60, 10, null, null, null, null, null, null, null, null, null, null, null, null, 339754, 340991, 342051, null, null, null, 372279, null, null, null, null, null, null, 382210).
openmaint_db     | 2023-07-16 11:10:38.745 UTC [112] STATEMENT:  INSERT INTO "Component" ("Code", "Name", "Description", "SerialNumber", "CISubset", "Type", "Brand", "Number", "Condition", "Criticality", "LastCheckDate", "Complex", "Building", "Floor", "Unit", "Room", "State", "PurchasePrice", "DisposalDate", "Life", "AmortizationStart", "AmortizationEnd", "AnnualAmortization", "FullyDepreciated", "WarrantyStart", "WarrantyEnd", "InstallationDate", "AcceptanceDate", "Weight", "ModelData", "Supplier", "Invoice", "NoiseLevel", "SystemPlant", "CI", "Dimensions", "ServiceStatus", "CalendarEntity", "IdTenant") VALUES ('10', '10', NULL, NULL, 379526, 339754, 372279, NULL, 280414, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 382605, NULL, NULL, NULL, 382210, NULL, 340991, 342051, NULL) RETURNING "Id"

Hope resolve soon

**Comment by Abady-01** [comment]
I resolve this problem by running docker-compose as showen in this reply https://github.com/itmicus/cmdbuild_docker/issues/38#issuecomment-1564887119 

So remove all command in file docker-compoes.yml in directory   **home/cmdbuild_docker/openmain2.3-3.4.1-d/docker-compse.yml** by this commands:



_version: "3.3"
volumes:
    openmaint-db:
    openmaint-tomcat:

services:
    openmaint_db:
        image: postgis/postgis:12-3.3-alpine
        container_name: openmaint_db
        volumes:
            - openmaint-db:/var/lib/postgresql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=*****
        restart: always

    openmaint_app:
        image: afcarvalho1991/cmdbuild:om-2.3-3.4.1-d
        container_name: openmaint_app
        links:
           - openmaint_db
        depends_on:
           - openmaint_db
        ports:
            - 8090:8080
        restart: always
        volumes:
            - openmaint-tomcat:/usr/local/tomcat
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=*****
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=openmaint_db
            - POSTGRES_DB=openmaint
            - CMDBUILD_DUMP=empty.dump.xz
            - JAVA_OPTS=-Xmx4000m -Xms2000m_

**Comment by Abady-01** [comment]
version: "3.3"
volumes:
    openmaint-db:
    openmaint-tomcat:

services:
    openmaint_db:
        image: postgis/postgis:12-3.3-alpine
        container_name: openmaint_db
        volumes:
            - openmaint-db:/var/lib/postgresql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=*****
        restart: always

    openmaint_app:
        image: afcarvalho1991/cmdbuild:om-2.3-3.4.1-d
        container_name: openmaint_app
        links:
           - openmaint_db
        depends_on:
           - openmaint_db
        ports:
            - 8090:8080
        restart: always
        volumes:
            - openmaint-tomcat:/usr/local/tomcat
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=*****
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=openmaint_db
            - POSTGRES_DB=openmaint
            - CMDBUILD_DUMP=empty.dump.xz
            - JAVA_OPTS=-Xmx4000m -Xms2000m

**Comment by itmicus** [comment]
thank you,
