### ISSUE TITLE
Manifest for itmicus/cmdbuild:r2u-2.0-3.2 not found: manifest unknown: manifest unknown.

### ISSUE THREAD

**Issue by afcarvalho-dev** [itmicus/cmdbuild_docker#9]
Hello,

I get this error

> Creating network "ready2use-20-32_default" with the default driver
Creating volume "ready2use-20-32_cmdbuild-db" with default driver
Creating volume "ready2use-20-32_cmdbuild-tomcat" with default driver
Pulling cmdbuild_app (itmicus/cmdbuild:r2u-2.0-3.2)...
manifest for itmicus/cmdbuild:r2u-2.0-3.2 not found: manifest unknown: manifest unknown

When trying to deploy using these commands:

`docker run --name cmdbuild_db -p 5432:5432 -d itmicus/cmdbuild:db-3.0
docker run --name cmdbuild_app --restart unless-stopped --link cmdbuild_db  -p 8090:8080 -d itmicus/cmdbuild:app-3.2`

Or trying to deploy via docker-compose by doing:

`
~/git/cmdbuild_docker/ready2use-2.0-3.2 (master)
$ docker-compose.exe up -d
`

Can you please help me solve this?
André

**Comment by itmicus** [comment]
Thank you, 
please check now, we had updated images in docker hub.

**Comment by afcarvalho-dev** [comment]
I was able to build the image (locally) using the sh file a few hours ago. 
That allowed me to solve the manifest problem. 

Thank you for your hard work!

Best regards,
André.

**Comment by itmicus** [comment]
Now, you can use images from docker hub
Thank you too
